// Generated by scripts/generate-screenshots.py. Do not edit by hand.
export const screenshotLocales = Object.freeze(["en", "de", "es", "fr", "it", "pt", "pt-br", "th", "pl", "cs", "hi", "hr", "hu", "ja", "ko", "ro", "ru", "sk", "sv", "tr", "id", "nb", "nl", "bg", "bn", "uk", "vi", "fil", "el", "sr", "sl", "fi", "ms", "da", "sw", "zh-cn", "zh-tw"]);

export const screenshotViews = Object.freeze({
  "calendar": {
    "width": 1144,
    "height": 2473,
    "layoutWidth": 420,
    "layoutHeight": 908
  },
  "appointments": {
    "width": 1144,
    "height": 2473,
    "layoutWidth": 420,
    "layoutHeight": 908
  },
  "reports": {
    "width": 1118,
    "height": 2473,
    "layoutWidth": 420,
    "layoutHeight": 929
  },
  "pdf": {
    "width": 2064,
    "height": 2545,
    "layoutWidth": 640,
    "layoutHeight": 789
  },
  "cloud": {
    "width": 2096,
    "height": 2040,
    "layoutWidth": 640,
    "layoutHeight": 623
  }
});
